### ISSUE TITLE
More power to your Selenium IDE scripts

### ISSUE THREAD

**Issue by peter-lyons-kehl** [mikeparrish/armyBMI#1]
Hi Mike,

Your ArmyBMI script runs `forXml...endForXml`. What Selenium IDE extension are you using - SelBlocks or some other?

You could empower your Selenium IDE scripts with @SeLite. @SeLite contains an enhanced version of SelBlocks, SelBlocks Global:  http://selite.github.io/SelBlocksGlobal.

@SeLite enables Selenese scripts to be more reusable and team-friendly. See http://selite.github.io.

**Comment by mikeparrish** [comment]
Good Afternoon Peter,

I am using SelBlocks. Thanks for the link and the info.

**Comment by peter-lyons-kehl** [comment]
Hi Mike,

Would you like to spread the word about your ArmyBMI test? Good news: GitHub is adding "topics", which are cross-repository tags. It was introduced only two days ago, but it's spreading fast.

Would you like to give your contribution a head start? Get on the train now, while the tracks are flexible: You can create your own topics. See https://github.com/blog/2309-introducing-topics.

Since your test can run in @SeLite, please could you connect our users: When you're adding topics to ArmyBMI, please would you link it to "selite".
